# Generated by tools/render-join.mjs. PowerShell 5.1 and 7.
# Installs verified Bun + p2p, joins chat, and never enables terminal access.
& {
  $ErrorActionPreference = 'Stop'
  Set-StrictMode -Version 2.0
  $joinKey = '0TMWBQG67V37JZ3GPRWVSSTSBJ'
  if ($joinKey -cnotmatch '^0[0123456789ABCDEFGHJKMNPQRSTVWXYZ]{25}$') { throw 'Invalid listener key' }
  Write-Host "Agent Tunnel: install verified Bun + p2p v0.3.6; connect chat to $joinKey."
  Write-Host 'Your machine name, username, OS and architecture will be sent to this peer.'
  Write-Host 'The chat daemon continues after this command exits. This join line does not enable remote terminal access.'
  $joinTemp = Join-Path ([IO.Path]::GetTempPath()) ('p2p-join-' + [Guid]::NewGuid().ToString('N'))
  $joinSaved = @{}
  $joinEnv = @{
    P2P_RUNTIME = 'bun'; P2P_REF = 'v0.3.6'
    P2P_SRC = 'https://github.com/fire17/p2p/releases/download/v0.3.6/p2p-v0.3.6.zip'
    P2P_SRC_SUMS = 'https://github.com/fire17/p2p/releases/download/v0.3.6/SHASUMS256.txt'
  }
  foreach ($joinName in $joinEnv.Keys) { $joinSaved[$joinName] = [Environment]::GetEnvironmentVariable($joinName, 'Process') }
  try {
    New-Item -ItemType Directory -Path $joinTemp | Out-Null
    try { [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 -bor [Net.ServicePointManager]::SecurityProtocol } catch {}
    $joinInstaller = Join-Path $joinTemp 'init.ps1'
    $ProgressPreference = 'SilentlyContinue'
    Invoke-WebRequest -UseBasicParsing -TimeoutSec 120 -Uri 'https://raw.githubusercontent.com/fire17/p2p/c26fde63ea01164bcbdb470e3c6a6f69682f748b/init.ps1' -OutFile $joinInstaller
    $joinHash = (Get-FileHash -LiteralPath $joinInstaller -Algorithm SHA256).Hash.ToLowerInvariant()
    if ($joinHash -ne 'd57e40fb2784c5780295a8cd6f10daa68c987aa7f04d720406fe1face4a077e9') { throw 'Installer SHA256 mismatch; nothing was executed' }
    foreach ($joinName in $joinEnv.Keys) { [Environment]::SetEnvironmentVariable($joinName, $joinEnv[$joinName], 'Process') }
    # Isolate the installer's explicit exit statements from the interactive owner shell.
    $joinShell = (Get-Process -Id $PID).Path
    & $joinShell -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $joinInstaller
    if ($LASTEXITCODE -ne 0) { throw "Verified installer failed (exit $LASTEXITCODE); see the p2p install.log" }
    $joinUserHome = if ($env:USERPROFILE) { $env:USERPROFILE } else { $HOME }
    $joinHome = if ($env:P2P_HOME) { $env:P2P_HOME } else { Join-Path $joinUserHome '.p2p' }
    if ((Get-Content -LiteralPath (Join-Path $joinHome 'runtime.kind') -Raw).Trim() -ne 'bun') { throw 'Installer did not select Bun' }
    $joinRuntime = (Get-Content -LiteralPath (Join-Path $joinHome 'runtime.path') -Raw -Encoding UTF8).Trim()
    if (-not (Test-Path -LiteralPath $joinRuntime -PathType Leaf)) { throw 'The installed Bun runtime is missing' }
    $joinHelper = Join-Path $joinTemp 'join.mjs'
    [IO.File]::WriteAllText($joinHelper, @'
// Embedded by render-join.mjs after the SHA-pinned installer succeeds.
// Only chat operations: local terminal permission is never requested or enabled here.
import { spawnSync } from 'node:child_process'
import { readdirSync, writeFileSync, unlinkSync } from 'node:fs'
import { hostname, userInfo, platform, arch } from 'node:os'
import { join, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'

async function main() {
const [key, home] = process.argv.slice(2)
const fail = (message, code = 2) => { throw Object.assign(new Error(message), { exitCode: code }) }
if (!/^0[0123456789ABCDEFGHJKMNPQRSTVWXYZ]{25}$/.test(key || '')) fail('invalid listener key')
if (!home) fail('installation home is missing')
if (!process.versions.bun) fail('the selected runtime is not Bun')
const app = join(resolve(home), 'app')
try { (await import(pathToFileURL(join(app, 'src', 'key.js')))).decodeKey(key) }
catch { fail('listener key checksum is invalid or the installed application is incomplete') }
const name = 'join-' + key
const bin = join(app, 'bin', 'p2p.js')
const env = { ...process.env, P2P_HOME: resolve(home) }
function cli(args, timeout = 45000) {
  const result = spawnSync(process.execPath, [bin, 'tunnel', ...args], {
    env, encoding: 'utf8', timeout, maxBuffer: 1024 * 1024,
    windowsHide: true, stdio: ['ignore', 'pipe', 'pipe'],
  })
  if (result.error) fail('CLI failed: ' + result.error.message, 3)
  return { code: result.status ?? 3, out: result.stdout || '', err: result.stderr || '' }
}
function status(sessionName) {
  const result = cli(['status', '--name', sessionName], 15000)
  if (result.code === 5) return null
  if (result.code !== 0) fail('cannot inspect session ' + sessionName + ': ' + result.err, result.code)
  try { return JSON.parse(result.out) } catch { fail('invalid daemon status for ' + sessionName, 3) }
}

// Reuse an existing authenticated connection, including one made by the older
// two-command prompt. A rerun must not replace its identity or start a second peer.
let names = []
try { names = readdirSync(join(home, 'tunnel'), { withFileTypes: true })
  .filter(entry => entry.isDirectory() && /^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/.test(entry.name)).map(entry => entry.name) }
catch (error) { if (error.code !== 'ENOENT') fail('cannot inspect existing tunnel sessions: ' + error.message, 3) }
if (names.length > 256) fail('too many local tunnel sessions; inspect them before joining', 2)
let selected = null
for (const candidate of [...new Set([name, 'default', ...names])]) {
  const state = status(candidate)
  if (!state?.alive) continue
  if (state.connected && state.peerKey === key) { selected = { name: candidate, state }; break }
  if (candidate === name) fail('this listener session already has a running daemon that is not connected to the requested peer; inspect it with p2p tunnel status --name ' + name, 2)
}

const clean = value => String(value).replace(/[\x00-\x1f\x7f]/g, ' ').slice(0, 200)
let username = 'unknown'
try { username = userInfo().username } catch {}
const identity = 'connected: ' + clean(hostname()) + ' ' + clean(username) + '\n' +
  JSON.stringify({ MACHINE: clean(hostname()), USER: clean(username), OS: platform(), ARCH: arch(), AGENT: 'bootstrap', RUNTIME: 'bun ' + process.versions.bun })
if (!selected) {
  // --profile is essential: the CLI otherwise creates an ephemeral identity on
  // each fresh session, which an already-bound host would correctly reject.
  const result = cli(['join', key, '--name', name, '--profile', name,
    '--say', 'Agent Tunnel connected; machine identification follows.', '--connect-timeout', '30'])
  if (result.code !== 0) fail(result.err.trim() || result.out.trim() || 'connection failed; the listener may be offline or already paired with another machine', result.code)
  const state = status(name)
  if (!state?.alive || !state.connected || state.peerKey !== key) fail('the requested peer did not become connected', 3)
  selected = { name, state }
}
// --file avoids PowerShell native argv quoting and never treats machine metadata
// or remote messages as shell syntax. Wait for a delivery acknowledgment.
const messageFile = join(resolve(home), '.join-' + process.pid + '-' + Date.now() + '.txt')
try {
  writeFileSync(messageFile, identity, { mode: 0o600, flag: 'wx' })
  const result = cli(['send', '--file', messageFile, '--name', selected.name, '--wait', '10'], 15000)
  if (result.code !== 0) fail('connected, but machine identification was not acknowledged; rerun to retry. ' + result.err.trim(), result.code)
} finally { try { unlinkSync(messageFile) } catch {} }
console.log('Agent Tunnel connected to ' + key + ' as ' + selected.state.self + '.')
console.log('Chat daemon is running in the background (PID ' + selected.state.pid + '). It does not start automatically after a reboot.')
console.log('Status: p2p tunnel status --name ' + selected.name)
console.log('Messages: p2p tunnel recv --name ' + selected.name + ' --wait 60')
console.log('Stop: p2p tunnel stop --name ' + selected.name)
console.log('Terminal activation is separate. This join line does not grant remote command execution.')
}
try { await main() } catch (error) { console.error('Agent Tunnel: ' + error.message); process.exitCode = error.exitCode || 3 }
'@, (New-Object Text.UTF8Encoding($false)))
    & $joinRuntime $joinHelper $joinKey $joinHome
    if ($LASTEXITCODE -ne 0) { throw "Agent Tunnel join failed (exit $LASTEXITCODE)" }
    # Native failures from deliberate earlier attempts must not poison a successful rerun.
    $global:LASTEXITCODE = 0
  } finally {
    foreach ($joinName in $joinSaved.Keys) { [Environment]::SetEnvironmentVariable($joinName, $joinSaved[$joinName], 'Process') }
    if (Test-Path -LiteralPath $joinTemp) { Remove-Item -LiteralPath $joinTemp -Recurse -Force -ErrorAction SilentlyContinue }
  }
}
