#!/usr/bin/env python3
"""Render the GENERIC Windows join script (join.ps1) — key as a parameter, never a per-key file.
join.sh is maintained by hand (same helper: tools/join-client.mjs is synced FROM join.sh's embedded copy)."""
import re, pathlib
here = pathlib.Path(__file__).resolve().parent; root = here.parent
tpl = (here / 'join-bootstrap.ps1.in').read_text()
rj = (here / 'render-join.mjs').read_text()
base = re.search(r"const base = '([^']+)'", rj).group(1)
m = re.search(r"ps1: \{ url: base \+ '([^']+)', sha256: '([a-f0-9]{64})'", rj)
helper = (here / 'join-client.mjs').read_text().rstrip()
assert "\n'@" not in helper, "helper would terminate the PowerShell here-string"
s = tpl.replace("# Generated by tools/render-join.mjs. PowerShell 5.1 and 7.\n# Installs verified Bun + p2p, joins chat, and never enables terminal access.\n",
"""# p2p.akeyo.io/join.ps1 — ONE static script for every Windows machine; the listener key is a PARAMETER, never a file on this site:
#   & ([scriptblock]::Create((irm https://p2p.akeyo.io/join.ps1))) <LISTENER_KEY>
# (share it as https://p2p.akeyo.io/#/join/<LISTENER_KEY> — the page renders this line client-side)
# Installs verified Bun + p2p v0.3.7, joins the listener's chat, identifies the machine. Never enables terminal access.
# Rendered from tools/join-bootstrap.ps1.in + tools/join-client.mjs by tools/render-generic.py. PowerShell 5.1 and 7.
param([Parameter(Position = 0)][string]$Key = '')
""")
s = s.replace("  $joinKey = '@@KEY@@'\n", "  $joinKey = $Key\n  if (-not $joinKey) { throw 'usage: & ([scriptblock]::Create((irm https://p2p.akeyo.io/join.ps1))) <LISTENER_KEY>' }\n")
s = s.replace('@@INSTALLER_URL@@', base + m.group(1)).replace('@@INSTALLER_SHA256@@', m.group(2)).replace('@@HELPER@@', helper)
assert '@@' not in s
(root / 'join.ps1').write_text(s, encoding='utf-8')
print('join.ps1 rendered', len(s), 'bytes')
